[package]
name = "pokemon"
version = "0.1.0"
edition = "2021"

[features]
default = ["real_data"]
real_data = []

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
serde_variant = "0.1.3"
